env:
  CIRRUS_CLONE_DEPTH: 3

# GNU sed, test everything.
linux_task:
  name: Linux
  container:
    image: ubuntu:22.04
    cpu: 1
    memory: 512M
  env:
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get -qy update >/dev/null
    - apt-get -qy install git php-cli shellcheck >/dev/null
    - ./regen_html_pages.sh
    - git status
    - test "$(git status --porcelain | wc -l)" -eq 0
    - php --syntax-check bpfexam/index.php
    - php --syntax-check manpages/restyle.php
    - shellcheck regen_man_pages.sh
    - shellcheck regen_html_pages.sh

# BSD sed, test one script only.
freebsd_task:
  name: FreeBSD
  freebsd_instance:
    cpu: 1
    memory: 1G
  script:
    - ./regen_html_pages.sh
    - git status
    - test "$(git status --porcelain | wc -l)" -eq 0
